CREATE TABLE Ruoli
(
	Id INT NOT NULL PRIMARY KEY IDENTITY, 
    Nome NVARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Utenti
(
	Id INT PRIMARY KEY IDENTITY,
	Nome NVARCHAR(100) NOT NULL,
	Cognome NVARCHAR(100) NOT NULL,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(512) NOT NULL,
	RuoloId INT NOT NULL,
	FOREIGN KEY (RuoloId) REFERENCES Ruoli(Id)
)
